// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7rPRmnldZHLdVfWXXc-8frRf-CQCFOgI',
    appId: '1:323697848346:web:9b03d694687b600d0861a3',
    messagingSenderId: '323697848346',
    projectId: 'project-data-44b25',
    authDomain: 'project-data-44b25.firebaseapp.com',
    storageBucket: 'project-data-44b25.appspot.com',
    measurementId: 'G-M9D2Q9VNM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCjWAVMLS1A6nRAXt24jKuTxf27BGizig',
    appId: '1:323697848346:android:8042f038fca3b4f60861a3',
    messagingSenderId: '323697848346',
    projectId: 'project-data-44b25',
    storageBucket: 'project-data-44b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDac4avLOxgHqIyoShis1M6mQEe4ghUeDE',
    appId: '1:323697848346:ios:d33a54d5a97661360861a3',
    messagingSenderId: '323697848346',
    projectId: 'project-data-44b25',
    storageBucket: 'project-data-44b25.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDac4avLOxgHqIyoShis1M6mQEe4ghUeDE',
    appId: '1:323697848346:ios:d33a54d5a97661360861a3',
    messagingSenderId: '323697848346',
    projectId: 'project-data-44b25',
    storageBucket: 'project-data-44b25.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7rPRmnldZHLdVfWXXc-8frRf-CQCFOgI',
    appId: '1:323697848346:web:ab6357677379ff260861a3',
    messagingSenderId: '323697848346',
    projectId: 'project-data-44b25',
    authDomain: 'project-data-44b25.firebaseapp.com',
    storageBucket: 'project-data-44b25.appspot.com',
    measurementId: 'G-TJ6R8P8K8V',
  );

}